language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: F6CVZWNOvpLASp/mdUrIKZ2A3ucen0UY/LoeH788kEeJ3dHrChAxoQi5Wmx+iMmvrFwud849IDaQ6Ui6GwSBtGUqY/xn7X01HdABkExpL6LcjTFOc9OLRtLOKVeW+amScN5+kesMbvPVxbOzpPwIIVQ+f493D6RaO4EQkCHJM/QrynKgkbDr0vYvy9bg4NMrLYIfCMS43X3vdrP+Wlr4/UAeDeByKh+bt7+l5htDLsxM6CPHQCTq//Sg8CWgNcob7Yl9Ny5A8Z1pQetaDngIS/1s4siTcdZgAu+2wRgsNmbst6n1WFUXFrqxcF9QGnN2EdwrKaZQD6F+V8+XNQDstU1FCReRhQX8wl8Dqwrv+mzxZVTnpqZje87jNGgSrQDEpv1lfsCLpHaYSC5K61DG+i3N9Qe9kD8+78MFp8hUj/8dsfrbArOzlim7106tVYwVZO9MBBJB4a4loPpzdnWhSgyCGMyycxn0qGVpITTqVf9J+6EabO3v7bBngbue4FRB+mOWvkNnTmus1JDkWmPLrOEtukrVKSDQ+l4iLnOSS2tZRzb29cZ3xFbGOFeMtBO5fQ+3n0gEko/9vwDSiXN1SqenoGe+YbDPNzdGl5ul4gF6hW0bRyRc/j1K7h4iGqZGvgyp1Ejv/bpI4wrKxiNN6aoXlPOPnbiF7x2XhkDWDcE=
  app: wishlist-social-app
  on:
    repo: brentguistwite/Wishlist
